export const SHEET_COLORS = {
  collection: {
    bg: 'bg-blue-50',
    bgSubtle: 'bg-blue-50/50',
    border: 'border-blue-200',
    borderAccent: 'border-l-blue-500',
    text: 'text-blue-700',
    textHeading: 'text-blue-800',
    icon: 'text-blue-500',
    dot: 'bg-blue-500',
    badge: 'bg-blue-100 text-blue-700',
    gradient: 'bg-gradient-to-r from-blue-500 to-blue-600',
    gradientSubtle: 'bg-gradient-to-br from-blue-50 to-blue-100/50',
    ring: 'ring-blue-200',
  },
  presse: {
    bg: 'bg-green-50',
    bgSubtle: 'bg-green-50/50',
    border: 'border-green-200',
    borderAccent: 'border-l-green-500',
    text: 'text-green-700',
    textHeading: 'text-green-800',
    icon: 'text-green-500',
    dot: 'bg-green-500',
    badge: 'bg-green-100 text-green-700',
    gradient: 'bg-gradient-to-r from-green-500 to-green-600',
    gradientSubtle: 'bg-gradient-to-br from-green-50 to-green-100/50',
    ring: 'ring-green-200',
  },
  prodParis: {
    bg: 'bg-teal-50',
    bgSubtle: 'bg-teal-50/50',
    border: 'border-teal-200',
    borderAccent: 'border-l-teal-500',
    text: 'text-teal-700',
    textHeading: 'text-teal-800',
    icon: 'text-teal-500',
    dot: 'bg-teal-500',
    badge: 'bg-teal-100 text-teal-700',
    gradient: 'bg-gradient-to-r from-teal-500 to-teal-600',
    gradientSubtle: 'bg-gradient-to-br from-teal-50 to-teal-100/50',
    ring: 'ring-teal-200',
  },
  prodDeloc: {
    bg: 'bg-violet-50',
    bgSubtle: 'bg-violet-50/50',
    border: 'border-violet-200',
    borderAccent: 'border-l-violet-500',
    text: 'text-violet-700',
    textHeading: 'text-violet-800',
    icon: 'text-violet-500',
    dot: 'bg-violet-500',
    badge: 'bg-violet-100 text-violet-700',
    gradient: 'bg-gradient-to-r from-violet-500 to-violet-600',
    gradientSubtle: 'bg-gradient-to-br from-violet-50 to-violet-100/50',
    ring: 'ring-violet-200',
  },
} as const;

export type SheetType = keyof typeof SHEET_COLORS;
